services:
  postgres:
    image: postgres:16
    container_name: viralfood-postgres
    restart: always
    environment:
      POSTGRES_DB: viralfood_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6574:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: viralfood-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@viralfood.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: