TRUNCATE TABLE orders.order_items RESTART IDENTITY CASCADE;
TRUNCATE TABLE orders.orders RESTART IDENTITY CASCADE;

TRUNCATE TABLE reservations.reservations RESTART IDENTITY CASCADE;
TRUNCATE TABLE reservations.restaurant_tables RESTART IDENTITY CASCADE;

TRUNCATE TABLE menu.menu_items RESTART IDENTITY CASCADE;
TRUNCATE TABLE menu.categories RESTART IDENTITY CASCADE;

TRUNCATE TABLE auth.admin_users RESTART IDENTITY CASCADE;