DROP TABLE IF EXISTS orders.order_items CASCADE;
DROP TABLE IF EXISTS orders.orders CASCADE;

DROP TABLE IF EXISTS reservations.reservations CASCADE;
DROP TABLE IF EXISTS reservations.restaurant_tables CASCADE;

DROP TABLE IF EXISTS menu.menu_items CASCADE;
DROP TABLE IF EXISTS menu.categories CASCADE;

DROP TABLE IF EXISTS auth.admin_users CASCADE;

DROP SCHEMA IF EXISTS orders CASCADE;
DROP SCHEMA IF EXISTS reservations CASCADE;
DROP SCHEMA IF EXISTS menu CASCADE;
DROP SCHEMA IF EXISTS auth CASCADE;